[package]
name = "biotoxin495/scrollframescaler"
description = "Automatically keeps a ScrollingFrame's CanvasSize fitted to its content."
version = "1.0.0"
license = "MIT"
authors = ["biotoxin495"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/biotoxin495/ScrollFrameScaler"

exclude = [
	"examples",
	"docs",
	".github",
	"*.rbxl",
	"*.rbxlx",
]